### ISSUE TITLE
double needle

### ISSUE THREAD

**Issue by stevemarion** [Mikhus/canv-gauge#33] opened 2015-02-02 15:57 UTC
Hello,
When I use multiple gauge at the same time, all except the first one get double needle
![gauge](https://cloud.githubusercontent.com/assets/10813528/6003459/42dcf72e-aafc-11e4-9d81-c587b93176d6.JPG)
These gauges are generated by the same code and should not difer
![gauge-code](https://cloud.githubusercontent.com/assets/10813528/6003478/65b3a6f8-aafc-11e4-9277-21c777350d61.JPG)
Thank you.

Edit 
double neelde ocur pretty randomly
![gauge_bug2](https://cloud.githubusercontent.com/assets/10813528/6004790/b6aeb512-ab05-11e4-8647-1058bc9aaba5.JPG)

**Comment by ctc** [comment] 2015-03-13 02:18
delay first value set by at least 250ms, then it works.

**Comment by stevemarion** [comment] 2015-04-03 13:18
I have found the source of the error. 
When providing data-value argument, the draw function is called twice, once when setting the value with setRawValue (l860) and once when calling drawing explicitely (l867).
As I don't use the JS api I have corrected my problem by commenting the draw on setRawValue, it works fine now.

**Comment by cpg** [comment] 2015-06-12 19:04
Can you produce a small bit of html with actual value (not variables) fo this so we can see it reproduced?

**Comment by Sieberkev** [comment] 2015-08-05 15:04
I came here with the same issue (sometimes I had >12 needles on different gauges, all completely random).

Setting the value in the gauge options (instead of using .setValue() as in the examples on the website) fixed the problem too.

**Comment by Mikhus** [comment] 2016-03-01 09:36
Can't reproduce it with the latest code. Could you, please, confirm issue still exists in a version 1.0.1 or later?

**Comment by Sieberkev** [comment] 2016-04-13 13:39
Updated to 1.0.2 today and using .setValue() on multiple gauges on the same page does not draw multiple needles anymore :smiley:

**Comment by Mikhus** [comment] 2016-04-14 10:21
OK, thank you, @Sieberkev! So I close this issue then.

**Closed by Mikhus** 2016-04-14 10:21 UTC

**Comment by nickleman** [comment] 2019-10-23 18:49
Is there a way I can intentionally get multiple needles on a gauge?
